language:
  - objective-c

env:
  matrix:
    - INSTALL_TYPE='macpython' VERSION=2.7.7
    - INSTALL_TYPE='macpython' VERSION=2.7.7 VENV=venv
#    - INSTALL_TYPE='macpython' VERSION=3.3.5
#    - INSTALL_TYPE='macpython' VERSION=3.3.5 VENV=venv
#    - INSTALL_TYPE='macpython' VERSION=3.4.1
#    - INSTALL_TYPE='macpython' VERSION=3.4.1 VENV=venv

install:
  - source ./travis_tools.sh
  - get_python_environment $INSTALL_TYPE $VERSION $VENV
   
script:
  - source test_tools.sh
  - $PIP_CMD install nose
  - $PIP_CMD install python-libsbml
  - nosetests test_travisparse.py
