os:
  - osx
  - linux

# language:
#  - g++
#  - objective-c

env:
  matrix:
#    - INSTALL_TYPE='macpython' VERSION=2.7.7
#    - INSTALL_TYPE='macpython' VERSION=2.7.7 VENV=venv
#    - INSTALL_TYPE='homebrew' VERSION=2.7.10
#    - INSTALL_TYPE='homebrew' VERSION=2.7.10 VENV=venv
#    - INSTALL_TYPE='macpython' VERSION=3.3.5
#    - INSTALL_TYPE='macpython' VERSION=3.3.5 VENV=venv
#    - INSTALL_TYPE='macpython' VERSION=3.4.1
#    - INSTALL_TYPE='macpython' VERSION=3.4.1 VENV=venv

install:
#  - source ./travis_tools.sh
#  - get_python_environment $INSTALL_TYPE $VERSION $VENV
  - echo $TRAVIS_OS_NAME
  - brew update
  - brew install python
  - brew tap homebrew/science
  - brew install libxml2
  - brew install libzip
  - brew install libsbml
  - brew link --overwrite python
  - /usr/local/bin/pip install --user python-libsbml

   
script:
#  - source test_tools.sh
#  - $PIP_CMD install nose
#  - nosetests test_travisparse.py
  - c++ test_prog.cpp -lsbml -lzip -lxml2 
  - ./a.out test_file.xml  out.xml
  - head out.xml
  - /usr/local/bin/python test_prog.py  test_file.xml  outy.xml
